version: 0.2

phases:
  install:
    commands:
      - echo Install no-op...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t circleci-test-docker-image .
      - docker tag circleci-test-docker-image:latest 421457959010.dkr.ecr.us-east-1.amazonaws.com/circleci-test-docker-image:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 421457959010.dkr.ecr.us-east-1.amazonaws.com/circleci-test-docker-image:latest
